sudo: false
language: go
go:
  - 1.10.x
  - 1.11.x
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -race -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
